# fly.toml app configuration file generated for fullstackopen-part3-vtyy on 2023-12-05T14:29:04+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopen-part3-vtyy"
primary_region = "hkg"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
